Funcionalidade/listagem de formas de pagamento em comum
jordisilvazup/desafio-gataway-de-pagamento pull request #2
Opened 2021-09-14 19:56 UTC by jordisilvazup

listagem das formas de pagamento que um determinado restaurante aceita de um determinado cliente

2021-09-15 13:26 UTC, yurioliveirazup requested changes

2021-09-15 13:26 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ConsultarFormasDePagamentoController.java
> +        List<FormasDePagamentoResponse> formasDePagamentoEmComum = restaurante.meiosDePagamentoPara(usuario)
Esse trecho de código ficou bem legal!

2021-09-15 13:26 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/ConsultarFormasDePagamentoEmComumRequest.java
> +public class ConsultarFormasDePagamentoEmComumRequest {
Em geral, colocamos verbos em classes que executam alguma ação (como as classes de serviços)... Nesse cenário, estamos com uma classe que transfere os dados, por que não colocar `FormasDePagamentoEmComumRequest`?

2021-09-16 10:48 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/ConsultarFormasDePagamentoEmComumRequest.java
> +public class ConsultarFormasDePagamentoEmComumRequest {
entendi, obrigado por compartilhar serei mais atencioso com as nomeações

2021-09-16 10:48 UTC, merged