Funcionalidade/listar em caso de fraude
jordisilvazup/desafio-gataway-de-pagamento pull request #3
Opened 2021-09-17 11:57 UTC by jordisilvazup

adicionando a causa de fraude no projeto

2021-09-17 19:35 UTC, yurioliveirazup requested changes

2021-09-17 19:35 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/fraude/Fraude.java
> +    private String email;
Esse email é o email do cliente? 
Por que não fazer o relacionamento?

2021-09-17 19:35 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/TipoPagamento.java
> +        public boolean disponibilidadeOffline() {
Por que não colocar esses dados como atributos? Do ponto de vista OO faz mais sentido ser um dado do que um comportamento, concorda?

2021-09-17 19:35 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/TipoPagamento.java
> +
Ideia de implementação

```java
TipoPagamento(boolean disponivelOffline) {
    this.disponivelOffline = disponivelOffline;
} 
```

2021-09-17 19:35 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/strategy/ListarFormasDePagamentoContext.java
> +        if(ehFraude){
Dá uma olhadinha nesse padrão: <https://refactoring.guru/design-patterns/chain-of-responsibility>

2021-09-17 19:35 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/strategy/ListarFormasDepagamentoStrategy.java
> +public interface ListarFormasDepagamentoStrategy {
Qual a vantagem dessa interface se não está usando polimorfismo? Toda operação é realizada por meio da `ListarFormasDePagamentoContext`

2021-09-24 14:12 UTC, yurioliveirazup approved these changes

2021-09-24 17:11 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/TipoPagamento.java
> +        public boolean disponibilidadeOffline() {
sim,  faz mais sentido.

2021-09-24 17:11 UTC, merged