finalizando o processamento de pagamento offline pt1
jordisilvazup/desafio-gataway-de-pagamento pull request #4
Opened 2021-09-29 14:44 UTC by jordisilvazup

2021-10-04 15:13 UTC, yurioliveirazup requested changes

2021-10-04 15:13 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    @Transactional
Essa anotação funciona nesse contexto?

2021-10-04 15:13 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    public Transacao paraTransacao(EntityManager manager, BigDecimal valor) {
Só pra ser um pouco chato. Aqui a pessoa consegue efetuar qualquer operação com o entityManager... como podemos deixar apenas a operação de `find`?

2021-10-04 15:13 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessarPagamentoController.java
> +            Transacao  transacao= request.paraTransacao(manager, valorDoPedido.get("valor"));
O que acontece se não tiver essa chave de `valor`?

2021-10-04 15:13 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    public Transacao paraTransacao(EntityManager manager, BigDecimal valor) {
Outro ponto, como você garante que esse valor é do pedido associado a essa transação, olhando apenas para esse método?

2021-10-04 15:13 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    @ExistId(domainClass = Restaurante.class)
Aqui é para ser `Restaurante.class` também?

2021-10-04 15:13 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    @ExistId(domainClass = Restaurante.class)
Mesma coisa aqui do comentário anterior

2021-10-04 15:13 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +        return new Transacao(restaurante,idPedido, valor,StatusTransacao.AGUARDANDO_CONFIRMACAO,formaDePagamento,usuario,informacoesExtras);
Esse construtor está com muitos parâmetros, por que não colocar um Builder?

2021-10-05 12:46 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    @Transactional
Não, porém a algumas discussões apuramos que sempre a transação mais acima será utilizada, e que se alguém utilizar determinado método, fora deste contexto a gente garantiria q teria uma transação.

2021-10-05 12:48 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    public Transacao paraTransacao(EntityManager manager, BigDecimal valor) {
Para garantir que apenas o find seja utilizado neste contexto, podemos  passar uma function como parâmetro, e utilizar o método apply.

2021-10-05 12:49 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    public Transacao paraTransacao(EntityManager manager, BigDecimal valor) {
Da forma modelada não temos garantia que este valor é referente  determinada transação, talvez uma solução para isso seja passar uma function, que receberá a chamada ao serviço externo.

2021-10-05 12:50 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessarPagamentoController.java
> +            Transacao  transacao= request.paraTransacao(manager, valorDoPedido.get("valor"));
é retornado null, e provavelmente estore uma exception no momento da consulta.

2021-10-05 12:51 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    @ExistId(domainClass = Restaurante.class)
não, foi falta de atenção :/ . my bad

2021-10-05 12:51 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +    @ExistId(domainClass = Restaurante.class)
não, foi falta de atenção :/ . my bad

2021-10-15 17:50 UTC, yurioliveirazup requested changes

2021-10-15 17:50 UTC, yurioliveirazup commented on pom.xml
> +			<artifactId>spring-cloud-starter-openfeign</artifactId>
Qual o timeout padrão para uma requisição do Feign? O que acontece se essa requisição durar 2 minutos? 
Será que vale a pena configurar isso?

2021-10-15 17:50 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessarPagamentoController.java
> +            BiFunction<Long,Class<?>,Object> find= (id,classe)-> manager.find(classe,id);
Acho que aqui eu trocaria a variável para algo como `findInDatabase` só pra deixar mais explícito, faz sentido?

2021-10-15 17:50 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +                AGUARDANDO_CONFIRMACAO,
Como esse é um valor padrão, por que não ter dois construtores ou usar um padrão como um static factory method?

2021-10-15 17:50 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/validators/FormaDePagamentoComumValidator.java
> +    public void validate(Object o, Errors errors) {
Esse código tá um pouco procedural, como podemos deixá-lo mais OO?

2021-10-15 17:50 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/validators/FormaDePagamentoComumValidator.java
> +    public void validate(Object o, Errors errors) {
Outro ponto, será que vale a pena deixar essas duas validações (usuário + forma de pagamento e restaurante + forma de pagamento) no mesmo Validator?

2021-10-15 18:30 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessarPagamentoController.java
> +            BiFunction<Long,Class<?>,Object> find= (id,classe)-> manager.find(classe,id);
concordo!

2021-10-15 18:47 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/validators/FormaDePagamentoComumValidator.java
> +    public void validate(Object o, Errors errors) {
sobre estar no mesmo Validator, acho que faz sentido, pois á validação é exatamente esta, se um restaurante e o cliente tem a mesma forma de pagamento. Dado que provavelmente ela será utilizada no momento de processar um pagamento online.

2021-10-15 18:57 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/request/PagamentoRequest.java
> +                AGUARDANDO_CONFIRMACAO,
acho que fará mais sentido no futuro. Um ponto que acho interessante sobre essa factory method é que poderia deixar mais semântico para cada um dos tipo de pagamento.

2021-10-18 13:27 UTC, jordisilvazup commented on pom.xml
> +			<artifactId>spring-cloud-starter-openfeign</artifactId>
O tempo padrão de conexão do client é 10 segundos, e o de leitura é 60 minutos. Se a requisição durar dois minutos, o sistema pode ficar lento,  ou seja, diminuir sua performance. 
Acredito que configurar o tempo padrão de leitura e conexão do client feign é uma ótima estratégia.

2021-10-21 18:48 UTC, yurioliveirazup approved these changes

2021-10-21 18:48 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pedidos/Pedido.java
> +    private BigDecimal valor;
O que acontece se o valor for negativo ou menor que zero?

2021-10-21 18:48 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/util/ResponseError.java
> +    public void adicionarPeloFieldError(FieldError fieldError) {
Usaria de sobrecarga de método aqui, mas bem legal a implementação

2021-10-21 18:48 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/validators/ExistPedidoValidator.java
> +        catch (Exception e){
O que acontece se subir qualquer outra exceção que não for a do Feign? Será que vale a pena tratar e devolver um 400 ou é melhor devolver um 5xx?

2021-10-21 18:48 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/validators/FormaDePagamentoComumValidator.java
> +                cliente -> {
Aqui acho que trocaria para `validator`

2021-10-22 13:51 UTC, merged