Funcionalidade/processando pagamento online
jordisilvazup/desafio-gataway-de-pagamento pull request #6
Opened 2021-11-10 15:26 UTC by jordisilvazup

2021-11-12 13:52 UTC, yurioliveirazup requested changes

2021-11-12 13:52 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/Gateway.java
> +    public Optional<TentativaPagamentoResponse> realizarPagamento(PagamentoRequest request, BigDecimal valorCompra){
Faz sentido receber uma classe de request aqui? Por que não criar um objeto de domínio para encapsular o valor da compra e o pagamento? 

Digo isso porque, se olharmos pelas camadas, temos uma classe de domínio dependendo de uma classe de aplicação...

2021-11-12 13:52 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/SaoriClient.java
> +    private String ENDERECO = "http://localhost:8080/api/saori/payment";
Valeria a pena pegar esse endereço do `application.properties`?

2021-11-12 13:52 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/TangoClient.java
> +    public TentativaPagamentoResponse realizarPagamento(PaymentExternalRequest request) {
Esses métodos são muito parecidos... acha que daria para centralizá-los em uma classe apenas?

2021-11-12 13:52 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/realizarPagamento/RealizarPagamentoSaori.java
> +        TentativaPagamentoResponse tentativaPagamentoResponse;
Precisa dessa variável aqui mesmo?

2021-11-12 13:52 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessaPagamento.java
> +    private PagamentoRequest pagamentoRequest;
Aqui acho que receberia a entidade também... tem algum custo a mais receber ela por aqui?

2021-11-12 13:52 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/SaoriClient.java
> +        ResponseEntity<TentativaPagamentoResponse> response = template.postForEntity(ENDERECO, payload, TentativaPagamentoResponse.class);
Qual o tempo padrão de uma chamada com `RestTemplate`? Será que vale a pena colocarum timeout?

2021-11-12 13:52 UTC, yurioliveirazup commented on src/test/java/br/com/zup/edu/desafiopagamentos/gateways/realizarPagamento/RealizarPagamentoSeyaTest.java
> +class RealizarPagamentoSeyaTest {
Os casos de teste estão bem interessante, mas nota como os testes nos clientes estão bem parecidos? Quando isso acontece, podemos pensar em alguma forma de refatorar o código de produção ou o código de testes... Faz sentido?

2021-11-16 13:14 UTC, jordisilvazup commented on src/test/java/br/com/zup/edu/desafiopagamentos/gateways/realizarPagamento/RealizarPagamentoSeyaTest.java
> +class RealizarPagamentoSeyaTest {
faz sentido demais meu querido, talvez vale a pena criar uma estrategia para testar os clients que são parecidos, alguma chamada em cadeia talvez?!

2021-11-16 13:32 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/TangoClient.java
> +    public TentativaPagamentoResponse realizarPagamento(PaymentExternalRequest request) {
Olhando para o futuro a forma de realizar o pagamento de cada um dos gateways podem evoluir de maneira diferentes, vejo que a modelagem utilizada estará preparada para que estas mudanças não impactem outros pontos do sistema.
Dado a isso eu acho que faz mais sentido utilizar uma técnica de testes onde centralize esses testes.

2021-11-16 13:37 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/SaoriClient.java
> +    private String ENDERECO = "http://localhost:8080/api/saori/payment";
caso fosse receber essas informações via application.properties seria necessário que o meu client seja um bean. E dado que não será possível utiliza-lo no contexto de pagamento como um bean acho que a melhor solução é que este endereço seja uma constante da classe.

2021-11-17 12:21 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessaPagamento.java
> +    private PagamentoRequest pagamentoRequest;
Talvaz aqui faça sentindo ter a logica de transformar em um pagamento, já colocar a entidade não vejo como pode ajudar.

2021-11-17 13:02 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/Gateway.java
> +    public Optional<TentativaPagamentoResponse> realizarPagamento(PagamentoRequest request, BigDecimal valorCompra){
realmente, faz sentido ter uma abstração que encapsula estes atributos.

2021-11-24 19:00 UTC, yurioliveirazup approved these changes

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/SeyaClient.java
> +    private String ENDERECO_BASE = "http://localhost:8080/api/seya";
Aqui eu colocaria um `final` para deixar como constante de fato

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/SeyaClient.java
> +    private RestTemplate template = GatewayClientFactory.getRestTemplate();
A mesma coisa do `final` aqui

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/realizarPagamento/RealizarPagamentoSaori.java
> +    private SaoriClient client = new SaoriClient();
Aqui não pode ser uma constante?

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/realizarPagamento/RealizarPagamentoSaori.java
> +            e.printStackTrace();
Daria para ficar em log de erro, não?

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessarPagamentoOnlineService.java
> +    private void pagamento(ProcessaPagamento processaPagamento, List<Gateway> gatewaysPorMenorCusto, Pagamento pagamento, ExecutorTransacional executorTransacional, BiFunction<Long, Class<?>, Object>
Acho que colocaria esse código em outra classe, talvez uma outra classe de serviço

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/pagamentos/ProcessarPagamentoOnlineService.java
> +    public ResponseEntity<?> realizarPagamento(ProcessaPagamento processaPagamento, ExecutorTransacional executorTransacional) {
Olha esse `ResponseEntity<?>`... faz sentido a gente ter uma dependência da camada de aplicação nesse serviço mais interno?

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/VerificacaoDeCartaoResponse.java
> +    public VerificacaoDeCartaoResponse() {
Vale um `@Deprecated` aqui, não?

2021-11-24 19:00 UTC, yurioliveirazup commented on src/main/java/br/com/zup/edu/desafiopagamentos/gateways/clients/GatewayClientFactory.java
> +                .setConnectionRequestTimeout(requestTimeout)
Massa o uso do timeout, a gente poderia pensar assim agora, se um serviço deu falha por X requisições seguidas, será que ele vai dar falha na próxima? Será que vale a pena a gente esperar um  pouco para fazer as requisições novamente? Não precisa implementar isso agora, mas acho que já vale ir pensando nessa problemática, o que acha?

2021-11-29 18:14 UTC, jordisilvazup commented
a

2021-11-29 18:14 UTC, merged